x-slides-base: &slides-base
  build:
    context: ./
    args:
      BUILDKIT_INLINE_CACHE: 1
  environment:
    - PRESENTATION_URL=${PRESENTATION_URL}
    - REPOSITORY_URL=${REPOSITORY_URL}
  user: ${CURRENT_UID}
  tmpfs:
    - ${BUILD_DIR} # Faster gulp I/O operations
  volumes:
    - ./content:/app/content
    - ./assets:/app/assets
    - ${DIST_DIR}:/app/dist
    - ./gulp/gulpfile.js:/app/gulpfile.js
    - ./gulp/tasks:/app/tasks
    - ./npm-packages:/app/npm-packages

services:
  serve:
    <<: *slides-base
    ports:
      - "8000:8000"

  build:
    <<: *slides-base
    depends_on:
      qrcode:
        condition: service_completed_successfully # Must NOT run in parallel
    entrypoint: >
      sh -xc 'gulp build && cp -r "${BUILD_DIR}"/* /app/dist/'

  qrcode:
    <<: *slides-base
    entrypoint: /app/node_modules/.bin/qrcode
    command: >
      -t png -o /app/content/media/qrcode.png ${PRESENTATION_URL}

  fat_pdf:
    image: ghcr.io/astefanutti/decktape:3.10.0
    depends_on:
      build:
        condition: service_completed_successfully # PDF is generated from the dist/index.html
    user: ${CURRENT_UID}
    volumes:
      - ${DIST_DIR}:/slides
    command: >
      /slides/index.html /slides/fat_slides.pdf --size='2048x1536' --pause 0

  pdf:
    image: vulhub/ghostscript:9.56.1
    depends_on:
      fat_pdf:
        condition: service_completed_successfully # The *BIG* PDF is there, ready to be WWched.
    user: ${CURRENT_UID}
    volumes:
      - ${DIST_DIR}:/slides
    command: >
        gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=/slides/slides.pdf /slides/fat_slides.pdf && rm /slides/fat_slides.pdf